name       : perl-devel-globaldestruction
version    : 0.14
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Devel-GlobalDestruction-0.14.tar.gz : 34b8a5f29991311468fe6913cadaba75fd5d2b0b3ee3bb41fe5b53efab9154ab
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::GlobalDestruction - Provides function returning the equivalent of `${^GLOBAL_PHASE} eq 'DESTRUCT'` for older perls
description: |
    Devel::GlobalDestruction - Provides function returning the equivalent of `${^GLOBAL_PHASE} eq 'DESTRUCT'` for older perls
builddeps  :
    - perl-sub-exporter-progressive
rundeps    :
    - perl-sub-exporter-progressive
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
